package ch.epfl.lamp.llvm

sealed abstract class ParameterAttribute(val syntax: String)
sealed abstract class ReturnAttribute(s: String) extends ParameterAttribute(s)
case object Zeroext extends ReturnAttribute("zeroext")
case object Signext extends ReturnAttribute("signext")
case object Inreg extends ReturnAttribute("inreg")
case object Byval extends ParameterAttribute("byval")
case object Sret extends ParameterAttribute("sret")
case object Noalias extends ReturnAttribute("noalias")
case object Nocapture extends ParameterAttribute("nocapture")
case object Nest extends ParameterAttribute("nest")

sealed abstract class FunctionAttribute(val syntax: String)
case class Alignstack(n: Int) extends FunctionAttribute("alignstack("+n.toString+")")
case object Alwaysinline extends FunctionAttribute("alwaysinline")
case object Inlinehint extends FunctionAttribute("inlinehint")
case object Noinline extends FunctionAttribute("noinline")
case object Optsize extends FunctionAttribute("optsize")
case object Noreturn extends FunctionAttribute("noreturn")
case object Nounwind extends FunctionAttribute("nounwind")
case object Readnone extends FunctionAttribute("readnone")
case object Readonly extends FunctionAttribute("readonly")
case object Ssp extends FunctionAttribute("ssp")
case object Sspreq extends FunctionAttribute("sspreq")
case object Noredzone extends FunctionAttribute("noredzone")
case object Noimplicitfloat extends FunctionAttribute("noimplicitfloat")
case object Naked extends FunctionAttribute("naked")
