%.object = type { %.class* }
%.class = type opaque
%java_Dlang_DObject = type %.object
%java_Dlang_DThrowable = type { %.object }
%java_Dlang_DException = type { %java_Dlang_DThrowable }
%java_Dio_DPrintStream = type { %.object }
%java_Dio_DPrintWriter = type { %.object }
%java_Dlang_DBoolean = type { %.object, i1 }
%java_Dlang_DByte = type { %.object, i8 }
%java_Dlang_DCharacter = type { %.object, i16 }
%java_Dlang_DDouble = type { %.object, double }
%java_Dlang_DFloat = type { %.object, float }
%java_Dlang_DInteger = type { %.object, i32 }
%java_Dlang_DLong = type { %.object, i64 }
%java_Dlang_DShort = type { %.object, i16 }
%java_Dlang_DString = type { %.object }
%java_Dlang_DThrowable = type { %.object }
%scala_DArray = type { %.object }
%scala_Druntime_DBoxedUnit = type { %.object }
